### ISSUE TITLE
I wish if.

### ISSUE THREAD

**Issue by khaledYS** [moinulmoin/vite-react-tailwind-starter#1]
I wish if you could make a package.json script that will allow us to build the tailwindcss .

**Comment by moinulmoin** [comment]
you are asking for a script to build only tailwind CSS separately?

**Comment by khaledYS** [comment]
> you are asking for a script to build only tailwind CSS separately?

If you could please .

**Comment by moinulmoin** [comment]
I will add that soon. Thank you.

**Comment by khaledYS** [comment]
> I will add that soon. Thank you.

Great. thanks.

**Comment by moinulmoin** [comment]
@khaledYS CSS build script is added. sorry for the delay :)

**Comment by khaledYS** [comment]
> @khaledYS CSS build script is added. sorry for the delay :)

Much thanks to you.
